version: 0.2
phases:
  install:
    commands:
      #install Node 12
      - echo installing node
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      #install dependencies
      - echo installing dependencies
      - npm install
  build:
    commands:
      #build
      - echo building
      - npm run build
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths /index.html /* /assets/*
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist