version: 0.2
phases:
  pre_build:
    commands:
      #install dependencies
      - echo installing dependencies
      - npm install
  build:
    commands:
      #build
      - echo building started on 'date'
      - npm run build
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths /*
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist